files:
  - source: /langsplit/en/**/name*.csv
    translation: /langsplit/%locale%/**/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,source_or_translation'
  - source: /langsplit/en/**/description*.csv
    translation: /langsplit/%locale%/**/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,source_or_translation'
  - source: /langsplit/en/**/source*.csv
    ignore:
      - source_url
    translation: /langsplit/%locale%/**/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,source_or_translation'
