files:
  - 
    source: /langsplit/en/ddf--concepts.csv/*
    translation: /langsplit/%locale%/ddf--concepts.csv/%original_file_name%
    first_line_contains_header: 1
    scheme: identifier,source_or_translation
