files:
  - source: /langsplit/en/**/*.csv
    ignore:
      - shape_lores_svg.csv
    translation: /langsplit/%locale%/**/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,source_or_translation'
